apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-chatbot-api-monitor
  namespace: ai-chatbot
  labels:
    app: ai-chatbot
    component: api
spec:
  selector:
    matchLabels:
      app: ai-chatbot
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s