apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-chatbot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: ai-chatbot
  app.kubernetes.io/part-of: ai-chatbot-system