name: CI/CD Pipeline

on:
  push:
    branches: [ main, demo ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r config/requirements/base.txt
        pip install pytest pytest-cov
    - name: Run tests
      run: pytest tests/ --cov=app
      continue-on-error: true

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
      run: docker-compose -f config/docker/compose/docker-compose.yml build
    - name: Test Docker compose
      run: |
        docker-compose -f config/docker/compose/docker-compose.yml up -d
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker-compose -f config/docker/compose/docker-compose.yml down