name: Diagnostic Check

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check repository structure
        run: |
          echo "=== Repository Structure ==="
          ls -la
          echo ""
          echo "=== Config Directory ==="
          ls -la config/ || echo "config/ not found"
          echo ""
          echo "=== Docker Directory ==="
          ls -la config/docker/ || echo "config/docker/ not found"
          echo ""
          echo "=== Requirements Directory ==="
          ls -la config/requirements/ || echo "config/requirements/ not found"
          echo ""
          echo "=== App Directory ==="
          ls -la app/ || echo "app/ not found"
          echo ""
          echo "=== API Directory ==="
          ls -la api/ || echo "api/ not found"
          echo ""
          echo "=== Tests Directory ==="
          ls -la tests/ || echo "tests/ not found"
      
      - name: Check Python files
        run: |
          echo "=== Python files in app/ ==="
          find app -name "*.py" -type f 2>/dev/null | head -20 || echo "No Python files in app/"
          echo ""
          echo "=== Python files in api/ ==="
          find api -name "*.py" -type f 2>/dev/null | head -20 || echo "No Python files in api/"
          echo ""
          echo "=== Python files in tests/ ==="
          find tests -name "*.py" -type f 2>/dev/null | head -20 || echo "No test files found"
      
      - name: Check requirements files
        run: |
          echo "=== Requirements files ==="
          echo "--- base.txt ---"
          cat config/requirements/base.txt 2>/dev/null | head -10 || echo "base.txt not found"
          echo ""
          echo "--- dev.txt ---"
          cat config/requirements/dev.txt 2>/dev/null | head -10 || echo "dev.txt not found"
          echo ""
          echo "--- prod.txt ---"
          cat config/requirements/prod.txt 2>/dev/null | head -10 || echo "prod.txt not found"
      
      - name: Test Python setup
        run: |
          python --version
          pip --version
          echo ""
          echo "=== Installing base requirements ==="
          pip install -r config/requirements/base.txt 2>&1 || echo "Failed to install base requirements"
          echo ""
          echo "=== Installing dev requirements ==="
          pip install -r config/requirements/dev.txt 2>&1 || echo "Failed to install dev requirements"
      
      - name: Check for app vs api directory
        run: |
          echo "=== Determining Python source directory ==="
          if [ -d "app" ] && [ -n "$(find app -name "*.py" -type f 2>/dev/null)" ]; then
            echo "✓ Found Python files in app/"
            echo "APP_DIR=app"
          elif [ -d "api" ] && [ -n "$(find api -name "*.py" -type f 2>/dev/null)" ]; then
            echo "✓ Found Python files in api/"
            echo "APP_DIR=api"
          else
            echo "✗ No Python source directory found"
          fi